/**
 * Song Contants
 */

export const SONG_ADD_REQUESTED = "SONG_ADD_REQUESTED";
export const SONG_ADD_SUCCEEDED = "SONG_ADD_SUCCEEDED";
export const RESET_SONG_ADD_SUCCEEDED = "RESET_SONG_ADD_SUCCEEDED";
export const SONG_ADD_FAILED = "SONG_ADD_FAILED";
export const RESET_SONG_ADD_FAILED = "RESET_SONG_ADD_FAILED";


export const GET_LIST_SONG = "GET_LIST_SONG";
export const GET_LIST_SONG_SUCCEEDED = "GET_LIST_SONG_SUCCEEDED";
export const GET_LIST_SONG_FAILED = "GET_LIST_SONG_FAILED";
export const RESET_ERROR_GET_LIST_SONG = "RESET_ERROR_GET_LIST_SONG";

export const SEARCH_SONG = "SEARCH_SONG";
export const SEARCH_SONG_SUCCEEDED = "SEARCH_SONG_SUCCEEDED";
export const SEARCH_SONG_FAILED = "SEARCH_SONG_FAILED";
export const RESET_ERROR_SEARCH_SONG = "RESET_ERROR_SEARCH_SONG";

export const GET_SONG_ID = "GET_SONG_ID";
export const GET_SONG_ID_SUCCEEDED = "GET_SONG_ID_SUCCEEDED";
export const GET_SONG_ID_FAILED = "GET_SONG_ID_FAILED";
export const RESET_ERROR_GET_SONG = "RESET_ERROR_GET_SONG";


export const DELETE_SONG_ID = "DELETE_SONG_ID";
export const DELETE_SONG_ID_SUCCEEDED = "DELETE_SONG_ID_SUCCEEDED";
export const DELETE_SONG_ID_FAILED = "DELETE_SONG_ID_FAILED";
export const RESET_SONG_DELETE_SUCCEEDED = "RESET_SONG_DELETE_SUCCEEDED";
export const RESET_SONG_DELETE_FAILED = "RESET_SONG_DELETE_FAILED";

export const SONG_EDIT_REQUESTED = "SONG_EDIT_REQUESTED";
export const SONG_EDIT_SUCCEEDED = "SONG_EDIT_SUCCEEDED";
export const SONG_EDIT_FAILED = "SONG_EDIT_FAILED";
export const RESET_SONG_EDIT_SUCCEEDED = "RESET_SONG_EDIT_SUCCEEDED";
export const RESET_SONG_EDIT_FAILED = "RESET_SONG_EDIT_FAILED";

export const GET_LIST_ID_SONG = "GET_LIST_ID_SONG";
export const GET_LIST_ID_SONG_SUCCESSED = "GET_LIST_ID_SONG_SUCCESSED";
export const GET_LIST_ID_SONG_FAILED = "GET_LIST_ID_SONG_FAILED";
/**
 * End Song Contants
 */



/**
 *  Artist Contants
 */
export const ARTIST_ADD_REQUESTED = "ARTIST_ADD_REQUESTED";
export const ARTIST_ADD_SUCCEEDED = "ARTIST_ADD_SUCCEEDED";
export const RESET_ARTIST_ADD_SUCCEEDED = "RESET_ARTIST_ADD_SUCCEEDED";
export const ARTIST_ADD_FAILED = "ARTIST_ADD_FAILED";
export const RESET_ARTIST_ADD_FAILED = "RESET_ARTIST_ADD_FAILED";


export const GET_LIST_ARTIST = "GET_LIST_ARTIST";
export const GET_LIST_ARTIST_SUCCEEDED = "GET_LIST_ARTIST_SUCCEEDED";
export const GET_LIST_ARTIST_FAILED = "GET_LIST_ARTIST_FAILED";
export const RESET_ERROR_GET_LIST_ARTIST = "RESET_ERROR_GET_LIST_ARTIST";

export const GET_ARTIST_ID = "GET_ARTIST_ID";
export const GET_ARTIST_ID_SUCCEEDED = "GET_ARTIST_ID_SUCCEEDED";
export const GET_ARTIST_ID_FAILED = "GET_ARTIST_ID_FAILED";
export const RESET_ERROR_GET_ARTIST = "RESET_ERROR_GET_ARTIST";

export const ARTIST_EDIT_REQUESTED = "ARTIST_EDIT_REQUESTED";
export const ARTIST_EDIT_SUCCEEDED = "ARTIST_EDIT_SUCCEEDED";
export const ARTIST_EDIT_FAILED = "ARTIST_EDIT_FAILED";
export const RESET_ARTIST_EDIT_SUCCEEDED = "RESET_ARTIST_EDIT_SUCCEEDED";
export const RESET_ARTIST_EDIT_FAILED = "RESET_ARTIST_EDIT_FAILED";

export const DELETE_ARTIST_ID = "DELETE_ARTIST_ID";
export const DELETE_ARTIST_ID_SUCCEEDED = "DELETE_ARTIST_ID_SUCCEEDED";
export const DELETE_ARTIST_ID_FAILED = "DELETE_ARTIST_ID_FAILED";
export const RESET_ARTIST_DELETE_SUCCEEDED = "RESET_ARTIST_DELETE_SUCCEEDED";
export const RESET_ARTIST_DELETE_FAILED = "RESET_ARTIST_DELETE_FAILED";

export const GET_LIST_ID_ARTIST = "GET_LIST_ID_ARTIST";
export const GET_LIST_ID_ARTIST_SUCCESSED = "GET_LIST_ID_ARTIST_SUCCESSED";
export const GET_LIST_ID_ARTIST_FAILED = "GET_LIST_ID_ARTIST_FAILED";
/**
 *  End Artist Contants
 */


/**
 *  Gallery Contants
 */

 export const GALLERY_ADD_REQUESTED = "GALLERY_ADD_REQUESTED";
 export const GALLERY_ADD_SUCCEEDED = "GALLERY_ADD_SUCCEEDED";
 export const RESET_GALLERY_ADD_SUCCEEDED = "RESET_GALLERY_ADD_SUCCEEDED";
 export const GALLERY_ADD_FAILED = "GALLERY_ADD_FAILED";
 export const RESET_GALLERY_ADD_FAILED = "RESET_GALLERY_ADD_FAILED";

export const GET_LIST_GALLERY = "GET_LIST_GALLERY";
export const GET_LIST_GALLERY_SUCCEEDED = "GET_LIST_GALLERY_SUCCEEDED";
export const GET_LIST_GALLERY_FAILED = "GET_LIST_GALLERY_FAILED";
export const RESET_ERROR_GET_LIST_GALLERY = "RESET_ERROR_GET_LIST_GALLERY";

export const GET_GALLERY_ID = "GET_GALLERY_ID";
export const GET_GALLERY_ID_SUCCEEDED = "GET_GALLERY_ID_SUCCEEDED";
export const GET_GALLERY_ID_FAILED = "GET_GALLERY_ID_FAILED";
export const RESET_ERROR_GET_GALLERY = "RESET_ERROR_GET_GALLERY";


export const DELETE_GALLERY_ID = "DELETE_GALLERY_ID";
export const DELETE_GALLERY_ID_SUCCEEDED = "DELETE_GALLERY_ID_SUCCEEDED";
export const DELETE_GALLERY_ID_FAILED = "DELETE_GALLERY_ID_FAILED";
export const RESET_GALLERY_DELETE_SUCCEEDED = "RESET_GALLERY_DELETE_SUCCEEDED";
export const RESET_GALLERY_DELETE_FAILED = "RESET_GALLERY_DELETE_FAILED";

export const GALLERY_EDIT_REQUESTED = "GALLERY_EDIT_REQUESTED";
export const GALLERY_EDIT_SUCCEEDED = "GALLERY_EDIT_SUCCEEDED";
export const GALLERY_EDIT_FAILED = "GALLERY_EDIT_FAILED";
export const RESET_GALLERY_EDIT_SUCCEEDED = "RESET_GALLERY_EDIT_SUCCEEDED";
export const RESET_GALLERY_EDIT_FAILED = "RESET_GALLERY_EDIT_FAILED";


/**
 *  End Gallery Contants
 */


/**
 *  Playlist Contants
 */


 export const CATEGORY_ADD_REQUESTED = "CATEGORY_ADD_REQUESTED";
 export const CATEGORY_ADD_SUCCEEDED = "CATEGORY_ADD_SUCCEEDED";
 export const RESET_CATEGORY_ADD_SUCCEEDED = "RESET_CATEGORY_ADD_SUCCEEDED";
 export const CATEGORY_ADD_FAILED = "CATEGORY_ADD_FAILED";
 export const RESET_CATEGORY_ADD_FAILED = "RESET_CATEGORY_ADD_FAILED";

export const GET_LIST_CATEGORY = "GET_LIST_CATEGORY";
export const GET_LIST_CATEGORY_SUCCEEDED = "GET_LIST_CATEGORY_SUCCEEDED";
export const GET_LIST_CATEGORY_FAILED = "GET_LIST_CATEGORY_FAILED";
export const RESET_ERROR_GET_LIST_CATEGORY = "RESET_ERROR_GET_LIST_CATEGORY";

export const GET_CATEGORY_ID = "GET_CATEGORY_ID";
export const GET_CATEGORY_ID_SUCCEEDED = "GET_CATEGORY_ID_SUCCEEDED";
export const GET_CATEGORY_ID_FAILED = "GET_CATEGORY_ID_FAILED";
export const RESET_ERROR_GET_CATEGORY = "RESET_ERROR_GET_CATEGORY";


export const DELETE_CATEGORY_ID = "DELETE_CATEGORY_ID";
export const DELETE_CATEGORY_ID_SUCCEEDED = "DELETE_CATEGORY_ID_SUCCEEDED";
export const DELETE_CATEGORY_ID_FAILED = "DELETE_CATEGORY_ID_FAILED";
export const RESET_CATEGORY_DELETE_SUCCEEDED = "RESET_CATEGORY_DELETE_SUCCEEDED";
export const RESET_CATEGORY_DELETE_FAILED = "RESET_CATEGORY_DELETE_FAILED";

export const CATEGORY_EDIT_REQUESTED = "CATEGORY_EDIT_REQUESTED";
export const CATEGORY_EDIT_SUCCEEDED = "CATEGORY_EDIT_SUCCEEDED";
export const CATEGORY_EDIT_FAILED = "CATEGORY_EDIT_FAILED";
export const RESET_CATEGORY_EDIT_SUCCEEDED = "RESET_CATEGORY_EDIT_SUCCEEDED";
export const RESET_CATEGORY_EDIT_FAILED = "RESET_CATEGORY_EDIT_FAILED";

export const GET_LIST_ID_CATEGORY = "GET_LIST_ID_CATEGORY";
export const GET_LIST_ID_CATEGORY_SUCCESSED = "GET_LIST_ID_CATEGORY_SUCCESSED";
export const GET_LIST_ID_CATEGORY_FAILED = "GET_LIST_ID_CATEGORY_FAILED";

/**
 *  End Category Contants
 */


/**
 *  UI Contants
 */

export const SET_IS_PLAY_SONG_TRUE = "SET_IS_PLAY_SONG_TRUE"
export const SET_IS_PLAY_SONG_FALSE = "SET_IS_PLAY_SONG_FALSE"

export const FETCH_PLAY_SONG_BY_ID = "FETCH_PLAY_SONG_BY_ID"
export const FETCH_PLAY_SONG_BY_ID_SUCCEEDED = "FETCH_PLAY_SONG_BY_ID_SUCCEEDED";
export const FETCH_PLAY_SONG_BY_ID_FAILED = "FETCH_PLAY_SONG_BY_ID_FAILED";
export const RESET_ERROR_FETCH_PLAY_SONG = "RESET_ERROR_FETCH_PLAY_SONG";

export const FETCH_GET_SONG_SUGGESTED_BY_ID = "FETCH_GET_SONG_SUGGESTED_BY_ID"
export const FETCH_GET_SONG_SUGGESTED_BY_ID_SUCCEEDED = "FETCH_GET_SONG_SUGGESTED_BY_ID_SUCCEEDED";
export const FETCH_GET_SONG_SUGGESTED_BY_ID_FAILED = "FETCH_GET_SONG_SUGGESTED_BY_ID_FAILED";
export const RESET_ERROR_FETCH_GET_SONG_SUGGESTED = "RESET_ERROR_FETCH_GET_SONG_SUGGESTED";

export const GET_SONG_RECOMMEND = "GET_SONG_RECOMMEND"
export const GET_SONG_RECOMMEND_SUCCEEDED = "GET_SONG_RECOMMEND_SUCCEEDED";
export const GET_SONG_RECOMMEND_FAILED = "GET_SONG_RECOMMEND_FAILED";
export const RESET_ERROR_GET_SONG_RECOMMEND= "RESET_ERROR_GET_SONG_RECOMMEND";



export const SONG_ADD_REQUESTED_ENDPOINT = "api/song/add";
export const ARTIST_ADD_REQUESTED_ENDPOINT = "api/artist/add";
export const GALLERY_ADD_REQUESTED_ENDPOINT = "api/gallery/add";
export const CATEGORY_ADD_REQUESTED_ENDPOINT = "api/category/add";


export const GET_LIST_SONG_ENDPOINT = "api/song/page";
export const GET_LIST_ARTIST_ENDPOINT = "api/artist/page";
export const GET_LIST_GALLERY_ENDPOINT = "api/gallery/page";
export const GET_LIST_CATEGORY_ENDPOINT = "api/category/page";



export const GET_SONG_BY_ID_ENDPOINT = "api/song";
export const GET_GALLERY_BY_ID_ENDPOINT = "api/gallery";
export const GET_CATEGORY_BY_ID_ENDPOINT = "api/category";
export const GET_ARTIST_BY_ID_ENDPOINT = "api/artist";

export const GET_SONG_SUGGESTED_BY_ID_ENDPOINT = "api/song/suggested";


export const EDIT_SONG_BY_ID_ENDPOINT = "api/song/edit";
export const EDIT_GALLERY_BY_ID_ENDPOINT = "api/gallery/edit";
export const EDIT_CATEGORY_BY_ID_ENDPOINT = "api/category/edit";
export const EDIT_ARTIST_BY_ID_ENDPOINT = "api/artist/edit";

export const DELETE_SONG_BY_ID_ENDPOINT = "api/song/delete";
export const DELETE_GALLERY_BY_ID_ENDPOINT = "api/gallery/delete";
export const DELETE_CATEGORY_BY_ID_ENDPOINT = "api/category/delete";
export const DELETE_ARTIST_BY_ID_ENDPOINT = "api/artist/delete";

export const GET_LIST_ID_ARTIST_ENDPOINT = "api/artist/getlist";
export const GET_LIST_ID_SONG_ENDPOINT = "api/song/getlist";
export const GET_LIST_ID_CATEGORY_ENDPOINT = "api/category/getlist";








export const SERVER_URL = 'https://server-imusic.herokuapp.com'
  // process.env.NODE_ENV === 'production' ? '' : 'http://localhost:5000';